---
env:
  es2020: true
extends:
  - standard
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  sourceType: module
plugins:
  - '@typescript-eslint'

overrides:
  # JSON files
  - files:
      - "*.json"
    extends:
      - plugin:jsonc/recommended-with-json
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSON
