---
env:
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  project: ./tsconfig.json
overrides:
  # JSON files
  - files:
      - "*.json"
    extends:
      - plugin:jsonc/recommended-with-json
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSON
